info:
  component: User Realm API for brightTALK test

spring:
  application:
    name: realm-api
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: create
  h2:
    console:
      enabled:true

server:
  port: ${PORT:${vcap.application.port:8017}}

logging:
  file: log/realm-api.log
  level:
    org:
      hibernate:
        type: trace

